# Ruff configuration (similar to pytest/requests style)
target-version = "py39"
line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
]

ignore = [
    "E501",  # line too long (handled by black)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex (let developers decide)
    "W191",  # indentation contains tabs
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "ARG",  # Unused arguments ok in tests
    "S101", # Assert ok in tests
]

[lint.isort]
known-first-party = ["genai_code_usage_monitor"]
force-single-line = false
lines-after-imports = 2
