blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/budlion/genai-code-usage-monitor/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/budlion/genai-code-usage-monitor#readme
    about: Read the project documentation
